apiVersion: v1
kind: Service
metadata:
  name: wms-api
  namespace: wms
  labels:
    app: wms-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: wms-api
  ports:
    - name: http
      port: 3030
      targetPort: 3030
      protocol: TCP
